openapi: 3.0.0
info:
  title: Simple To-Do List API
  description: Un'API di esempio per gestire una lista di attività da fare.
  version: "1.0.0"

servers:
  - url: https://api.example.com/v1
    description: Server di produzione

paths:
  /todos:
    get:
      summary: Ottieni tutte le attività
      description: Restituisce un elenco di tutte le attività (To-Do).
      responses:
        '200':
          description: Un array di oggetti To-Do.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Crea una nuova attività
      description: Aggiunge una nuova attività alla lista.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTodo'
      responses:
        '201':
          description: Attività creata con successo.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'

  /todos/{todoId}:
    get:
      summary: Ottieni una singola attività
      description: Restituisce i dettagli di una specifica attività tramite il suo ID.
      parameters:
        - name: todoId
          in: path
          required: true
          description: L'ID dell'attività da recuperare.
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Dettagli dell'attività.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Attività non trovata.

    delete:
      summary: Cancella un'attività
      description: Rimuove un'attività dalla lista tramite il suo ID.
      parameters:
        - name: todoId
          in: path
          required: true
          description: L'ID dell'attività da cancellare.
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Attività cancellata con successo.

components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID univoco dell'attività.
          example: 1
        title:
          type: string
          description: Il titolo o la descrizione dell'attività.
          example: "Comprare il latte"
        completed:
          type: boolean
          description: Indica se l'attività è stata completata.
          example: false
    NewTodo:
      type: object
      properties:
        title:
          type: string
          description: Il titolo o la descrizione dell'attività.
          example: "Chiamare il commercialista"